version: '3.7'

services:
  influxdb:
    restart: always
    image: influxdb:1.7.11-alpine
    environment:
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_DB
      - INFLUXDB_HTTP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
    - influxdb-data:/var/lib/influxdb
    ports:
      - 8086:8086
    mem_limit: 5g
    networks:
      - monitoring

  grafana:
    restart: always
    image: grafana/grafana
    environment:
      - GF_SERVER_ROUTER_LOGGING
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
      - INFLUXDB_DB
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana/:/etc/grafana/provisioning
    ports:
      - 3000:3000
    networks:
      - monitoring

  # elasticsearch-datagen:
  #   image: oliver006/es-test-data
  #   command:
  #     - --es_url=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - monitoring

  elasticsearch:
    restart: always
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    mem_limit: 2g
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - monitoring

  alertmanager:
    restart: always
    image: prom/alertmanager:v0.23.0
    ports:
      - 9093:9093
    volumes:
      - ./configs/alertmanager/:/etc/alertmanager/
    networks:
      - monitoring
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  prometheus:
    restart: always
    image: prom/prometheus:v2.30.0
    volumes:
      - ./configs/prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  influxdb-data:
  grafana-data:
  elasticsearch-data:
  prometheus-data:

