global:
  resolve_timeout: 1m
  slack_api_url: '${SLACK_WEBHOOK_URL_INFRASTRUCTURE_ALERTS_0}'

route:
  receiver: slack
  group_by:
  - alertname
  - env
  routes:
  - receiver: slack
    match:
      severity: page|warning
    continue: true

receivers:
- name: slack
  slack_configs:
  - channel: '#infrastructure-alerts'
    send_resolved: true
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for .{{ .CommonLabels.env }} env
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:* {{ range .Labels.SortedPairs }}{{ if or (eq .Name "app") (eq .Name "job") (eq .Name "service") }} 
       • *{{ .Name }}:* `{{ .Value }}`{{ end }}{{ end }}
     {{ end }}
