# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: monitoring
    static_configs:
    - targets:
      - influxdb:8086
      - grafana:3000
      - prometheus:9090
      - alertmanager:9093
      - elasticsearch_exporter:9114
      - blackbox_exporter:9115
      labels:
        container: monitoring
        app: monitoring
        env: org

  - job_name: off-net
    static_configs:
    - targets: 
      - 10.1.0.110:9113 # NGINX
      - 10.1.0.110:9117 # Apache
      labels:
        container: off-net
        app: "off"
        env: net

  - job_name: robotoff-net
    static_configs:
    - targets: 
      - 10.1.0.119:9102 # StatsD Gunicorn
      labels:
        container: robotoff-net
        app: robotoff
        env: net

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_probe] 
    static_configs:
      - targets:
        - https://monitoring.openfoodfacts.org
        - https://world.openfoodfacts.net
        - https://world.openfoodfacts.org
        - https://robotoff.openfoodfacts.net/api/v1/insights
        - https://robotoff.openfoodfacts.org/api/v1/insights
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.

  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.cadvisor'
  #     type: 'A'
  #     port: 8080
  #   static_configs:
  #        - targets: ['cadvisor:8080']

  # - job_name: 'node-exporter'
  #   scrape_interval: 5s
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.node-exporter'
  #     type: 'A'
  #     port: 9100

  # - job_name: 'pushgateway'
  #   scrape_interval: 10s
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.pushgateway'
  #     type: 'A'
  #     port: 9091

  #     static_configs:
  #         - targets: ['node-exporter:9100']
