# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: off-net
    scrape_interval: 5s
    static_configs:
    - targets: 
      - 10.1.0.110:9113 # NGINX
      - 10.1.0.110:9117 # Apache
      labels:
        app: "off"
        env: net

  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.cadvisor'
  #     type: 'A'
  #     port: 8080
  #   static_configs:
  #        - targets: ['cadvisor:8080']

  # - job_name: 'node-exporter'
  #   scrape_interval: 5s
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.node-exporter'
  #     type: 'A'
  #     port: 9100

  # - job_name: 'pushgateway'
  #   scrape_interval: 10s
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.pushgateway'
  #     type: 'A'
  #     port: 9091

  #     static_configs:
  #         - targets: ['node-exporter:9100']
