apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false

  - name: ElasticSearch (Metrics)
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[metrics-]YYYY.MM.DD"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 70

  - name: ElasticSearch (Logs)
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[logs-]YYYY.MM.DD"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 70

  - name: InfluxDB
    type: influxdb
    access: proxy
    database: ${INFLUXDB_DB}
    url: http://influxdb:8086
    editable: true
    basicAuth: true
    basicAuthUser: ${INFLUXDB_ADMIN_USER}
    secureJsonData:
      basicAuthPassword: ${INFLUXDB_ADMIN_PASSWORD}
